### ISSUE TITLE
Earth Defense Crashes on Launch

### ISSUE THREAD

**Issue by Xukkorz** [SmokeMonsterPacks/Mega-Sg-Jailbreak#100]
(do not submit bugs if you are using any means of powering your Mega Sg other than the OEM power supply. Only use the original PSU and USB cable when bug testing)

**Describe the bug**
Launch game Earth Defense - No intro version Sha1 is 9BF4CDA850495D7811DF578592289018862DF575

**To Reproduce**
1. Load game crashes instantly

**Expected behavior**
Game loads to start menu.

**Screenshots**

**Firmware version**
Only submit reports for the latest jailbreak or official firmware (please be ready to retest your issue if the firmware is updated). Latest version

**Relevant Mega Sg settings**

**ROM name and hash values**
Earth Defense ~ Earth Defend, The (USA, Asia) (Unl)
Sha1 9BF4CDA850495D7811DF578592289018862DF575

**Additional context**
Add any other context about the problem here:

**Comment by tjanas** [comment]
Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
