### ISSUE TITLE
MegaSD does not load 32X roms on JB 7.8

### ISSUE THREAD

**Issue by RevQuixo** [SmokeMonsterPacks/Mega-Sg-Jailbreak#101]
Roms (with the exception of Spider-Man: Web of Fire) load on 4.8 using the MegaSD (hard reset in options).  They have worked in prior fw as well.

7.8 introduced a fix for Spider-Man: Web of Fire that causes  all 32X roms to black screen when using the MegaSD.  You can reset (Up + Start) and load cartridge again a couple of times and usually trick the MegaSD into loading the game but never on first boot.  Assuming whatever timing /reset change was made for Spider-Man broke everything else (including Spider-Man)

**Comment by scottlinux** [comment]
Same behavior as #95

**Comment by BooBerry** [comment]
If your 32X is a revision VA0, you'll need the 32X Expansion Unit (aka the bus terminator) connected to the expansion port when using it with a Mega Sg.

More detail about that here: https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak/issues/95#issuecomment-1537141751

**Comment by tjanas** [comment]
@RevQuixo what is the behavior with the latest official firmware?

**Comment by tjanas** [comment]
@RevQuixo Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB

**Comment by tjanas** [comment]
Closing issue here since JB7.8 is no longer supported and should be tested with JB7.9, and tracked in the new repo.
