### ISSUE TITLE
Original Ultracore game cartridge (Japanese version) does not work on Mega Sg.

### ISSUE THREAD

**Issue by DanielMedeiros-1987** [SmokeMonsterPacks/Mega-Sg-Jailbreak#102]
My original Ultracore game cartridge (Japanese version) didn't work on Mega Sg, but it works perfectly on my Mega Drive 3 (Tectoy / PAL-M).

**Comment by tjanas** [comment]
@DanielMedeiros-1987 please re-test with the new firmware update https://www.analogue.co/support/mega-sg/firmware/4.9

**Comment by tjanas** [comment]
Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
