### ISSUE TITLE
SMS Core Fails Frame IRQ HCount Test

### ISSUE THREAD

**Issue by ajgowans** [SmokeMonsterPacks/Mega-Sg-Jailbreak#104]
The SMS core fails the "Frame IRQ HCount" test in the attached VDPTEST rom. You can compare to the same test run on a PAL SMS2, also attached.

I have attached the full test results for the SG (on latest JB FW, but being run off of a flashcard) and PAL SMS2, and also the current MiSTer core which may be of interest
![SMS Test - SG 3](https://user-images.githubusercontent.com/45233473/137819435-083b3c50-79f2-4686-b53b-8ef8c3c3f600.jpeg)
.
![SMS Test - PAL MS2 - 03](https://user-images.githubusercontent.com/45233473/137819476-281aad97-69d8-463d-884a-19dbb75432ea.jpeg)
[VDPTEST.sms.zip](https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak/files/7369067/VDPTEST.sms.zip)
[SMS Test Mega SG (15-Oct-2021).zip](https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak/files/7369068/SMS.Test.Mega.SG.15-Oct-2021.zip)
[SMS Test PAL MS2 (15-Oct-2021).zip](https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak/files/7369069/SMS.Test.PAL.MS2.15-Oct-2021.zip)
[SMS Test MiSTer (29-Sep-2021).zip](https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak/files/7369070/SMS.Test.MiSTer.29-Sep-2021.zip)

**Comment by tjanas** [comment]
@ajgowans can you re-test with your flash cart using https://www.analogue.co/support/mega-sg/firmware/4.9

**Comment by tjanas** [comment]
@ajgowans Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB

**Comment by tjanas** [comment]
Per JB7.9 changelog:
Fixed SMS IRQ Hcount test.
