### ISSUE TITLE
Load SMS bios so we can watch the intro/play bios games

### ISSUE THREAD

**Issue by PizzaCube** [SmokeMonsterPacks/Mega-Sg-Jailbreak#106]
can we  load sega master system bios with out a game in it to watch the  amazing intro  also the bios with games on them. 

https://youtu.be/TvBoqQH1y_U

i tried it and the japan one does not work but the usa does...

also you cant play the hidden game in the bios unless you can boot it with out a cart in it

https://youtu.be/ek7wLTJq-5w

**Comment by tjanas** [comment]
@PizzaCube Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
