### ISSUE TITLE
Outback joey does not boot.

### ISSUE THREAD

**Issue by PizzaCube** [SmokeMonsterPacks/Mega-Sg-Jailbreak#107]
The Rom of outback joey wont boot on the current firmware it just stays black

**Comment by tjanas** [comment]
Can you provide checksum information? What if the rom is loaded via everdrive instead of JB?

**Comment by tjanas** [comment]
Please re-test with JB7.9 and if the issue still exists, please open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
