### ISSUE TITLE
Sonic blast on game gear title screen has graphic dots

### ISSUE THREAD

**Issue by PizzaCube** [SmokeMonsterPacks/Mega-Sg-Jailbreak#108]
Sonic blast on game gear title screen has graphic dots.  

they look like c ram dots but they are on the title screen and they should not be there . its a real cart with the game gear adapter

there might be more problems with this game it is hard to tell because it is so buggy

**Comment by tjanas** [comment]
@PizzaCube Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
