### ISSUE TITLE
Game Gear 4:3 width presets incorrect

### ISSUE THREAD

**Issue by kingpost** [SmokeMonsterPacks/Mega-Sg-Jailbreak#11]
In jailbreak 7.3 using the Game Gear core, the width presets for "4:3 for 16:9" are not correct.

Here are the values they should be for each height preset:

```
Height | 4:3 Width
5.0x      960
5.5x     1056
6.0x     1152
6.5x     1248
7.0x     1344
7.5x     1440
```

**Comment by frederic-mahe** [comment]
The Game Gear resolution is 160 ×144. I think you are applying the following formula:

height = 144 * multiplier * 4/3

It seems to me that formula is valid only for the width, not the height, but I might be wrong. Could someone please confirm this?

**Comment by kingpost** [comment]
I'm specifically discussing width values, not height.

**Comment by kingpost** [comment]
Mr. Mahe, is there any other confirmation you need?  Please note I have reaffirmed the issue is with the "4:3" horizontal/width presets, not the height. Thanks.

**Comment by frederic-mahe** [comment]
@kingpost I need another Mega Sg user to confirm your observations so I can tag this issue as a bug. But don't worry, tagged or not, all open issues are considered when preparing a new firmware release.

**Comment by frederic-mahe** [comment]
Somewhat related to your issue @kingpost ,FirebrandX has posted a video on that topic. He says that the correct values for Game Gear at 7.0x are  1310 by 1008 px (see https://youtu.be/dzVu05ACVhc?t=2890), corresponding to "square pixels", and the closest you can get to the actual ratio of a Game Gear screen.

**Comment by Brianvgplayer** [comment]
Firebrand X later suggested 1344x1008 for GG instead of 1310x1008.

**Comment by Firebrandx** [comment]
My original preset was based on someone else's crude measurements of the Game Gear screen. However, I later found the service manual PDF, and the actual dimensions almost perfectly match 960x720 at 5x and 1344x1008 at 7x. So each integer scale should follow that graph. The OP is correct so long as the vertical scale is also honored.

**Comment by zxtheproto** [comment]
1428 by 1071, in my experience, fills the screen in the 1.33:1 aspect ratio without cutting off detail.

**Comment by tjanas** [comment]
@kingpost Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
