### ISSUE TITLE
No MD5 file for 7.8 release

### ISSUE THREAD

**Issue by wirehack7** [SmokeMonsterPacks/Mega-Sg-Jailbreak#111]
The .md5 file is missing for the latest release to verify the downloaded firmware. Could this be addded by the dev please?

**Comment by frederic-mahe** [comment]
yes, the `md5` file is missing from the original 7.8 release (2021-02-22), but it was added to the repository 15 months ago if you need it:

https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak/blob/master/firmware/msg_firmware_verJB7.8.md5

I'd prefer not to create a new release just for the `md5` file.

**Comment by tjanas** [comment]
@frederic-mahe can you add it if/when a new JB firmware is added?
