### ISSUE TITLE
Columbus Circle 2019 cartridges Gleylancer and 16bit Rhythm Land no longer work under firmware 7.7/7.8

### ISSUE THREAD

**Issue by nihilisation** [SmokeMonsterPacks/Mega-Sg-Jailbreak#113]
Mega Drive Columbus Circle's 2019 cartridge releases "Gleylancer" and "16bit Rhythm Land" no longer work/boot under firmware 7.7 onward. They are working with firmware up to 7.6/4.6 .

Describe the bug:
Attempts of booting 2019 "GleyLancer" or "16bit Rhythm land" cartridges give a black screen

To Reproduce:
Insert cart, power on, run cart

Firmware version:
7.7 and 7.8, worked fine on 7.6 or "official" 4.6

**Comment by tjanas** [comment]
Can you please re-test with the latest official firmware?

**Comment by tjanas** [comment]
@nihilisation it was reported as fixed with https://www.analogue.co/support/mega-sg/firmware/4.9

**Comment by nihilisation** [comment]
@tjanas I cannot test currently. I will update this post in a few days, around 12/05/2023. Thanks for the heads up, I would have missed the last update without your comment !

**Comment by tjanas** [comment]
Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB

**Comment by tjanas** [comment]
Per JB7.9 changelog:
Added support for Columbus Circle games (16 Bit Rhythm Land, etc).
