### ISSUE TITLE
Demons of Asteborg

### ISSUE THREAD

**Issue by L10N37** [SmokeMonsterPacks/Mega-Sg-Jailbreak#115]
Demons of AssBurg still won't load. Got it on release. Patch that allows use on everdrive doesn't work for JB megaSG

**Comment by bferrara** [comment]
The new release, Astebros, does not work either.

**Comment by tjanas** [comment]
Is this a cartridge or digital release? If the latter, can you provide checksums for the file that did not load?

**Comment by L10N37** [comment]
please also fix demons

**Comment by tjanas** [comment]
> please also fix demons

Is this a cartridge or digital release? If the latter, can you provide checksums for the file that did not load?

**Comment by bferrara** [comment]
> Is this a cartridge or digital release? If the latter, can you provide checksums for the file that did not load?

This is for the digital release of Astebros. My cartridge is on pre-order.

SHA256 hash of Astebros_V1.bin:
cec20d4e64d2a5f060a88f6ed10c7c9a75531bfcf84e6015016d51d0b5bbe25c

**Comment by tjanas** [comment]
> > Is this a cartridge or digital release? If the latter, can you provide checksums for the file that did not load?
> 
> This is for the digital release of Astebros. My cartridge is on pre-order.
> 
> SHA256 hash of Astebros_V1.bin: cec20d4e64d2a5f060a88f6ed10c7c9a75531bfcf84e6015016d51d0b5bbe25c

Please re-test with today’s JB update.

**Comment by tjanas** [comment]
@L10N37 @bferrara Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB

**Comment by L10N37** [comment]
The ROM starts off with corruption, continues ok, starts up and crashes to a white screen during the intro clip bit.
