### ISSUE TITLE
add release 7.9 to "firmware"-folder

### ISSUE THREAD

**Issue by 4ch1m** [SmokeMonsterPacks/Mega-Sg-Jailbreak#119]
@tjanas, could you please add the new release ([v7.9](https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak/releases/tag/v7.9)) to the [firmware](https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak/tree/master/firmware) folder?

Thanks a lot! :+1:

**Comment by whitezombie2000** [comment]
It seems there is a new repository for these releases. Probably because SmokeMonster doesn't want to manage them anymore.

https://github.com/analoguejb

**Comment by tjanas** [comment]
Resolved via https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak/commit/8b2511ed9e380a02730f997fe011b1342e0841b9
