### ISSUE TITLE
Feature Request: Save cheat codes and button option

### ISSUE THREAD

**Issue by Rageypoo** [SmokeMonsterPacks/Mega-Sg-Jailbreak#14]
Hello, thank you for the JB and all the hard work you've done. I had a feature request if possible. 

It would be fantastic if the cheat codes you enter for each game were able to be saved to the SD and used for future use. It's a bit frustrating not being able to save them and once the system is powered down they go away. 

It would also be awesome if we could have an additional button for scrolling through the letters and numbers for the codes. Right now you can only start from A and work your way down, setting another button to go backwards (to start from 9 and work your way back) would be SO fantastic. 

I understand this is a minor request and you are busy with other things, this would be so appreciated if it could be implimented not just for Mega SG but for Super NT as well. Thank you so much! 

-Ragey

**Comment by SmokeMonsterPacks** [comment]
Cool ideas, but I don't foresee either of these features being implemented, so I will go ahead and close this to declutter the issues tracker.
