### ISSUE TITLE
Feature Request: Quicker access to dither blending filter

### ISSUE THREAD

**Issue by TheRealFlamepanther** [SmokeMonsterPacks/Mega-Sg-Jailbreak#17]
The dither filter is practically mandatory for games like Final Fight CD that rely on dithering excessively. But it also produces artifacts or blurs out fine details, so you definitely don't want to leave it on for games that don't need it. This is pretty different from screen size or scan lines, which you'd typically set once and leave alone. My preference would be to have a hotkey. But I'll settle for anything quicker than opening the menu, going to "video", moving down a few lines to open "extra features", and then moving down a couple more lines to toggle the filter.

**Comment by SmokeMonsterPacks** [comment]
I think it's hidden in "extra features" on purpose. But this is an official firmware request.
