### ISSUE TITLE
Firmware version 4.3 is out of date

### ISSUE THREAD

**Issue by zxtheproto** [SmokeMonsterPacks/Mega-Sg-Jailbreak#20]
A new version of the OS was released, with several bug fixes. As this jailbreak is based on 4.3, several bugs could be remedied by updating the jailbreak firmware to the new version.

https://support.analogue.co/hc/en-us/articles/360024836892-Mega-Sg-Firmware-Update-v4-4

**Comment by frederic-mahe** [comment]
@zxtheproto A new jailbreak firmware is available.
