### ISSUE TITLE
Sega CD - Vay - Blue Screen During Intro

### ISSUE THREAD

**Issue by FrJosh** [SmokeMonsterPacks/Mega-Sg-Jailbreak#22]
## Expected behavior and actual behavior
When starting a new game the screen turns blue during the intro and a short section of the audio (the guy talking to you) keeps repeating over and over.

## Steps to reproduce the problem
Just start a new game and watch the intro

Firmware: 7.4

**Comment by jairulnait** [comment]
I experienced the same issue. Model 2 SCD and JB7.4.

**Comment by GreatHierophant** [comment]
Ditto

**Comment by BooBerry** [comment]
This issue has been fixed in the official 4.5 firmware.

https://support.analogue.co/hc/en-us/articles/360024836892-Mega-Sg-Firmware-Update-v4-5

**Comment by alexcom84** [comment]
Tested and working as intended on fw 4.5.

**Comment by frederic-mahe** [comment]
It should also be fixed in the jailbreak firmware. @alexcom84 it would be great if you could make the test.

**Comment by alexcom84** [comment]
Working well on jb 7.5 !
