### ISSUE TITLE
Sega CD - Popful Mail - MAIN-CPU ERROR !!

### ISSUE THREAD

**Issue by FrJosh** [SmokeMonsterPacks/Mega-Sg-Jailbreak#23]
## Expected behavior and actual behavior
When you get to the "Press Start" to play main screen, after pressing start the screen goes black with a bunch of text on it.  `MAIN-CPU ERROR !!`  followed by a bunch of random code.

Firmware: 7.4

**Comment by jairulnait** [comment]
Again, also experiencing the same issue. It was previously working with JB7.3.

**Comment by GreatHierophant** [comment]
Same here.

**Comment by Vorenge** [comment]
Same issue here. This error occurs after the new game into video. I have the original game and the model 2 Sega CD.

**Comment by bmichelmd** [comment]
The first time I ran it I made it past the intro but now it stops at or around the intro with the same CPU error.

**Comment by mattsolomon419** [comment]
Same CPU error here. 1st time Sega CD owner. Wanted to play this game real bad.

**Comment by frederic-mahe** [comment]
@mattsolomon419 I cannot test it myself, but the game seems to run fine with [jailbreak firmware7.3](https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak/blob/master/firmware/msg_firmware_verJB7.3.bin).

**Comment by BooBerry** [comment]
This issue has been fixed in the official 4.5 firmware.

https://support.analogue.co/hc/en-us/articles/360024836892-Mega-Sg-Firmware-Update-v4-5

**Comment by alexcom84** [comment]
Tested and working great on fw 4.5.
