### ISSUE TITLE
Update features to new firmware release - V.4.5

### ISSUE THREAD

**Issue by zxtheproto** [SmokeMonsterPacks/Mega-Sg-Jailbreak#37]
The newest version of Analogue's official firmware has been released, fixing many bugs and adding features over the previous version. It therefore makes sense to upgrade the jailbreak firmware to include these additions.

version 4.5 notes from Analogue's website:

- Player 2 controller can run the menu if it is a 3 or 6 button controller, and player 1 controller is not a 3 or 6 button controller.
- Different size font files are supported. If the file is 1K or larger, the first 32 characters are cut off.
- DVI Mode was added.
- Fixed scaler bug where the top scanline or two might not be visible.
- Scanlines have been totally redone. There are now more options to tweak and width is now adjustable.

(gen/md)
- fixed CD games that regressed in previous fw
- Some graphic issues on Mickey Mania CD and others fixed.
- Fixed bugs with Japanese Sega CDs.
- Silpheed and Vay bugs fixed.
- Popful Mail "CPU ERROR" fixed.
- CD bus timing improvements.
- Pier Solar cartridge + audio CD works and tested on US model 1, US model 2, and Japanese CD units.
- Added an option to automatically enable CD audio when CD unit plugged in.
- Fixed FM sound bug on Streets of Rage percussion on certain tracks.
- Fixed PSG sound bug (Phantasy Star IV).
- CRAM dots option added.
- X-Men 2 random character select on start is now random.

(sms)
- SMS Cropping setting added to crop the left side when a game used left cut.
- Fixed PSG sound bug (Alex Kidd in Miracle World).
- CRAM dots option added.
- VDP palette option added to select SMS or original TMS9918a palette for video modes 0-3.
- All 240 scanlines are now visible. Before, only 239 were visible.

**Comment by frederic-mahe** [comment]
The new jailbreak is out.
