### ISSUE TITLE
Certain audio options have been removed in Coleco core via JB.7.5

### ISSUE THREAD

**Issue by SegaSnatcher** [SmokeMonsterPacks/Mega-Sg-Jailbreak#38]
This core no longer has the options to apply advanced filter settings, swap left and right audio, or cartridge volume adjust.  There was no mention of this downgrade, so perhaps it was a mistake by the writer of this firmware.

**Comment by mholzinger** [comment]
We could close this issue. The Coleco audio options are in the latest 7.7 jailbreak.

Headphone Settings: 
- Volume[0 - 50]
- High Impedence phones [enable/disable]

Channel Levels: [all defaulted to 60]
- Square 1 [0-100]
- Square 2 [0-100]
- Square 3 [0-100]
- Noise [0-100]
- SGM 1 [0-100]
- SGM 2 [0-100]
- SGM 3 [0-100]

Channel panning: [-100 (left) + 100 (right)] (defaults shown below)
- Square 1 [-32]
- Square 2 [+32]
- Square 3 [0]
- Noise [0]
- SGM 1 [-32]
- SGM 2 [+32]
- SGM 3 [0]

-3db output cut [enable/disable]

**Comment by SmokeMonsterPacks** [comment]
Excellent, thank you @mholzinger!

**Comment by SegaSnatcher** [comment]
Hi,  sorry, must have confused my original post.   I was referring to Low Pass Filter options and left/right swap.  Those use to be in the Coleco core and then were removed and are still gone in curent JB.

**Comment by tjanas** [comment]
@SegaSnatcher Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB

**Comment by tjanas** [comment]
Per JB7.9 changelog:
Coleco's filter option menu is back.
