### ISSUE TITLE
[Master System] [JB 7.5] Rastan Saga: YM music is missing notes.

### ISSUE THREAD

**Issue by vanfanel** [SmokeMonsterPacks/Mega-Sg-Jailbreak#42]
Hi,

Using "Rastan (USA, Europe).sms", music with YM enabled is missing a lot of notes.
Seems like a timing issue to me.

Any confirmation with original cartridge would be welcome.

Thanks!

**Comment by SegaSnatcher** [comment]
Joe from GameSack mentioned SMS FM sounding off in Rastan via Official firmware as well. 

[https://youtu.be/VT2hJE3b_tQ?t=857](url)

**Comment by Brianvgplayer** [comment]
I don't have the cart, but the sound in the ROM plays correctly using the Everdrive X7 FM sound instead of the sound from the Mega SG.

**Comment by vanfanel** [comment]
> I don't have the cart, but the sound in the ROM plays correctly using the Everdrive X7 FM sound instead of the sound from the Mega SG.

Then the SMS YM implementation is to blame. I do not see how running the game from a cartidge would make a difference, but well, in case someone can confirm...

**Comment by zxtheproto** [comment]
> Then the SMS YM implementation on the MegaSG is to blame. I do not see how running the game from a cartidge would make a difference, but well, in case someone can confirm...

The Everdrive X7 has its own emulated synthesizer for YM2413 titles, which it passes through the cartridge audio header of the Genesis. There is also a cartridge adapter with a real YM2413 chip called the Powerbase Mini FM, which behaves similarly.

**Comment by ultrahealthy** [comment]
I've had the same problem when using the official firmware, I'm assuming this means the jailbreak doesn't fix it. Another person said the same thing happens with Altered Beast, which also uses FM sound.

In my case, deselecting the Use FM Sound box simply turned the music off altogether, it didn't revert to PSG

**Comment by skooterblog** [comment]
Here is my video of Rastan on JB 7.6, from yesterday:
https://www.youtube.com/watch?v=jX9RgFDTF9g

And here is my video Rastan on PowerBase Mini FM (real discrete YM2413), from four years ago, on an original Sega Genesis:
https://www.youtube.com/watch?v=BoAnZH-tsx0

I can't compare them now (workplace, can't hear music), but I hope they can help.

**Comment by mholzinger** [comment]
Jailbreak 7.7 - Compared audio from the SMS core to the video referencing GameSack. The FM emulation on the fpga doesn't appear to have any changes, so this might still be an issue.

>> Joe from GameSack mentioned SMS FM sounding off in Rastan via Official firmware as well.
>> https://youtu.be/VT2hJE3b_tQ?t=857

**Comment by SegaSnatcher** [comment]
This issue is not simply related to JB.   Kevtris has stated his FM SMS implemtation needs work, but he doesn't have time to fix it anytime soon.

**Comment by skooterblog** [comment]
We should NOT buy any Analogue stuff until this bug is fixed. They won't fix if we keep buying their half-baked products.

**Comment by zxtheproto** [comment]
I wouldn’t go that far. It’s certainly an issue, but in the grand scale of things it’s pretty minor.
I know it can be obnoxious, but have patience. A fix is in progress.

**Comment by tjanas** [comment]
@vanfanel Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB

**Comment by vanfanel** [comment]
Yes, the same issue happens with JB 7.9 FW. Opened issue there.

**Comment by tjanas** [comment]
Moved to https://github.com/analoguejb/Analogue-Mega-Sg-JB/issues/3
