### ISSUE TITLE
Please add cart dumping to the Mega Sg.

### ISSUE THREAD

**Issue by amoore2600** [SmokeMonsterPacks/Mega-Sg-Jailbreak#44]
Given all the different cart types the Mega Sg can play, adding cart dumping would be a nice bonus. On the Super NT I have really enjoyed backing up my library and using my original copies between my devices. It's also been wonderful to back back up may save ram too. The only other option I wish existed would be to inject the the save ram back on to the cart as this would make swapping batteries much easier.

**Comment by WNivek** [comment]
I concur; the SuperNT jailbreak's cart dumper was a fantastic feature, and one I would love to see translated to the MegaSG jailbreak.

**Comment by TheRealFlamepanther** [comment]
Yes please!

**Comment by frederic-mahe** [comment]
Duly noted. I am going to close that issue for now.

**Comment by justinoue** [comment]
Is this something that's still in the pipe?
