### ISSUE TITLE
Hardball '95 - "SRAM failure"

### ISSUE THREAD

**Issue by zxtheproto** [SmokeMonsterPacks/Mega-Sg-Jailbreak#45]
**Describe the bug**
When loading Hardball '95 from the Genesis core, it gives an error message when trying to boot the game against a red screen.

**To Reproduce**
1. Load ROM 'HardBall '95 (USA).md'.
2. Run game past SEGA logo.
3. See error message - should read as such:

"Cartridge Error Message:
SRAM failure
Press RESET to restart."

**Expected behavior**
The red screen is expected to either not appear or appear very briefly before continuing to the game, without an error message. (See [here](https://www.youtube.com/watch?v=OXwG-xZQ1bs) or [here](https://www.youtube.com/watch?v=_yidJsBiKMc).) The short red screen appearance seems to be more common in emulators, though neither seems to impede gameplay.

**Firmware version**
This was tested with the newest jailbreak firmware as of this writing, JBv7.5.

**ROM name and hash values**

File Name: Hardball '95 (USA).md
MD5: e5b12f2b4e4ff18a838bfec88ec0a601
SHA1: 6a63fba59add9ba8e1845cbfcf4722833893113f

**Comment by bumfacekilla** [comment]
Can confirm the same error on JB7.4. Using the ROM identified as 'Hardball '95 (U) [F1]' by GoodTools works normally.

**Comment by frederic-mahe** [comment]
OK, this could be a bad ROM issue. The ROM used by @zxtheproto is marked as unverified by [dat-o-matic](https://datomatic.no-intro.org/?page=show_record&s=32&n=0584). A re-dump might be necessary. Until then, maybe someone could try with an original cartridge?

**Comment by zxtheproto** [comment]
Just ordered a copy of the cartridge to test; it should be here by July 1. 

I did locate a copy of the SRAM patched ROM, and while it does boot it also doesn't save. Moreover, some elements appear to be corrupt and unalterable, such as the tournament names and logos accessible from the settings.

**Comment by zxtheproto** [comment]
The SRAM features do appear to work correctly on an original cartridge:

![ex1](https://user-images.githubusercontent.com/27112784/60400270-59011980-9b3f-11e9-8955-6ca197eef9a6.png)

![ex2](https://user-images.githubusercontent.com/27112784/60400271-5b637380-9b3f-11e9-8693-eee99407d56b.png)


I also tried ripping my own cartridge to a ROM image with my Retrode. 

File Name: HardBall '95 (1995).bin

MD5: e5b12f2b4e4ff18a838bfec88ec0a601
SHA1: 6a63fba59add9ba8e1845cbfcf4722833893113f

This ROM image also doesn't boot on the Mega SG, giving the same error.

I should also note that, while emulators are not a baseline for real hardware performance, they can read and write to the game's SRAM. This, along with the identical hash values between the two ROM images, implies that the original dump is likely correct.

**Comment by BooBerry** [comment]
This should be fixed in the new jailbreak firmware released today. :)
