### ISSUE TITLE
Might and Magic 3 Battery Ram Error

### ISSUE THREAD

**Issue by thomas83lin** [SmokeMonsterPacks/Mega-Sg-Jailbreak#48]
Can't start a new game in might and magic 3 cause of "Could not initialize  battery ram.

Firmware verJB7.5

possible there is a setting or something I'm missing???

**Comment by bumfacekilla** [comment]
The ROM identified as "Might and Magic III - Isles of Terra (U) [h1C]" by GoodTools works and saves fine. This game never saw a retail release, so there is no proper dump of the finished product.

**Comment by thomas83lin** [comment]
Thanks, that was the problem, was using the b1 version.
