### ISSUE TITLE
Flickering pixels in Firmware, JB7.6, reverting to 7.5 corrected issue.

### ISSUE THREAD

**Issue by RowanUnderwood** [SmokeMonsterPacks/Mega-Sg-Jailbreak#59]
**Describe the bug**
Flickering pixels in all tested games in Firmware, JB7.6, reverting to 7.5 corrected issue.  Tried both from cart and from SD card, all other settings stock.  https://i.imgur.com/A7jsz5s.mp4 is what it looks like (this is slowed down for better visibility).  My display is an oled55c9pua, running straight through with provided HDMI cable.
 

**To Reproduce**
1. install firmware 7.6
2. Load any rom / cart
3. pixels flicker

**Expected behavior**
Nice sharp pixels like in 7.5 :)

**Screenshots**
https://i.imgur.com/A7jsz5s.mp4

**Relevant Mega Sg settings**
all other settings stock

**Comment by frederic-mahe** [comment]
@RowanUnderwood I took the liberty to trim your post. Do you get these flickering pixels only in SMS games or in Megadrive games too? Is your issue related to issue #57 ?

**Comment by RowanUnderwood** [comment]
Yup I believe it's the same as #57, sorry about that, didn't see that one
in there.  Didn't get a chance to test any SMS games on this firmware
revision, but saw the noise in every Mega Drive game I tried, including
real carts and from SD card.  We should ask Leonprotos what TV he is using,
maybe it's related to that?  Mine is a oled55c9pua running in game mode.

**Comment by frederic-mahe** [comment]
No problem. I am going to close that issue.
