### ISSUE TITLE
Screen cut off on GG games on JB 7.6

### ISSUE THREAD

**Issue by Brianvgplayer** [SmokeMonsterPacks/Mega-Sg-Jailbreak#62]
I noticed the top line of the GG screen is cut off on some games (including Ms. Pac-Man and Mortal Kombat), no matter which resolution or aspect ratio I set it to. The screen seems to move slightly when switching filters. Screen is still cut off after the settings were reset. I'm on Jailbreak 7.6.

Edit: I checked 7.5 and the graphics aren't cut off on GG games, but they were cut off again when I went back to 7.6, so it had nothing to do with switching filters.

**Comment by Brianvgplayer** [comment]
Anyone else have this issue? It's most noticeable on MK where part of the intro message at the top of the screen is cut off. Any word on JB 7.7 and if it will fix this issue?

**Comment by BooBerry** [comment]
Jailbreak 7.7 is now out. Is it still cut off?

**Comment by Brianvgplayer** [comment]
I checked a few games. Image is no longer cut off at the top.

**Comment by SmokeMonsterPacks** [comment]
Thanks!
