### ISSUE TITLE
Gley Lancer 2019 reprint no longer working on 7.7

### ISSUE THREAD

**Issue by Steven-Pendleton** [SmokeMonsterPacks/Mega-Sg-Jailbreak#65]
It looks like 7.7 doesn't like the official Gley Lancer reprint. My 1992 cart works fine, but the new one no longer works despite working on previous firmware.

Describe the bug
Gley Lancer 2019 gives only a black screen

To Reproduce
Insert cart, power on, run cart

Firmware version
7.7. Worked on 7.6.

**Comment by tjanas** [comment]
@Steven-Pendleton please re-test with https://www.analogue.co/support/mega-sg/firmware/4.9

**Comment by tjanas** [comment]
@Steven-Pendleton Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
