### ISSUE TITLE
Metal Blast 2277

### ISSUE THREAD

**Issue by Indcsion** [SmokeMonsterPacks/Mega-Sg-Jailbreak#66]
Audio plays too fast. Someone tested it on there model 1 and it also played to fast. I tested it on 2 model 2s (va1.8 and va2.3) and a cdx and it plays correctly. Here's a demo rom to test with. https://gcup.itch.io/metal-blast-2277 
This is what it should sound like.
https://www.youtube.com/watch?v=ce0ORVozr3g
It seems to play fine on kega fusion but not on blastem.

**Comment by Steven-Pendleton** [comment]
Tested the demo on Mega Sg, Nomad, and Japanese Mega Drive. The music is too fast on the Mega Sg and YM3438 busy behaviour on/off doesn't change anything.

**Comment by tjanas** [comment]
@Indcsion Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
