### ISSUE TITLE
Allow the user to customize the mapping of Coleco Vision controller.

### ISSUE THREAD

**Issue by frgagnon** [SmokeMonsterPacks/Mega-Sg-Jailbreak#67]
It would be great if we could change the mapping between the buttons on the Genesis controller and the various buttons on the Coleco Vision controller somewhere in the options.

The jailbreak manual provide the definition of the default/hard-coded mapping, but it would be nice if the user could define his own custom mapping in the core options.

Depending on the game, it might make sense to map some "numbers" directly to the basic "ABC-XYZ" buttons instead of the default D-Pad direction + button.

This is not a mandatory feature since the hard-coded mapping allows the user to play games. But it 
is a nice to have as playability for some games would be improved.

For instance, the mouse trap game requires the following actions:
- trigger red gates (1, Y-right)
- trigger yellow gates (2, Y-down)
- trigger blue gates (3, Y-left)
- transform into dog (5, Z-right)

I would ideally map them to something like: a,b,c, and z respectfully.

**Comment by SmokeMonsterPacks** [comment]
This didn't show up in the latest update so I'm closing the request to focus attention on bugs.
