### ISSUE TITLE
Shin Megami Tensei (Mega-CD) crashing on 7.7

### ISSUE THREAD

**Issue by Steven-Pendleton** [SmokeMonsterPacks/Mega-Sg-Jailbreak#68]
Describe the bug
Shin Megami Tensei crashes upon getting to the name entry screen

To Reproduce
Start new game, get to name entry screen

Firmware version
4.7 and 7.7
Reverting to 4.6 fixes this.

I am using the MegaSD as my Mega-CD does not work with my Mega Sg, so I'm unable to test what happens with a real Mega-CD + Mega Sg combo.

**Comment by BooBerry** [comment]
Hi there, a group of us have been testing these issues using the new firmware that was released a couple days ago and it looks like Shin Megami Tensei works fine with the MegaSD and the Mega Sg running firmware 4.8 (official) or 7.8 (jailbreak).

You might give it a go and see if the issue still remains for you. :)
