### ISSUE TITLE
Steel Empire Graphic Errors on Stage 3

### ISSUE THREAD

**Issue by barbaro00** [SmokeMonsterPacks/Mega-Sg-Jailbreak#69]
Hi,

I have load the Steel Empire USA rom and always have image errors on the scroll, you can see the picture:

![IMG_1181](https://user-images.githubusercontent.com/44876637/74057193-ae5dad00-49e3-11ea-8932-e84380139d8f.JPG)

Thank you for your work is awesome!!

**Comment by Steven-Pendleton** [comment]
Tested with both Japanese and US roms both from the Mega Sg cores menu and also on MegaSD. This never appeared on any of the 4 tests. I played it legit the first time, and then used the level select cheat to get there the other 3 times. I am also pretty sure this is stage 4, not 3.

**Comment by frederic-mahe** [comment]
I am going to close that issue as it could be due to a bad ROM. Feel free to re-open the issue if the bug can be reproduced with a valid ROM or an original cartridge.
