### ISSUE TITLE
320 and 256 modes with same horizontal width do not line up

### ISSUE THREAD

**Issue by Steven-Pendleton** [SmokeMonsterPacks/Mega-Sg-Jailbreak#73]
(do not submit bugs if you are using any means of powering your Mega Sg other than the OEM power supply. Only use the original PSU and USB cable when bug testing)

**Describe the bug**
Set horizontal width for both 320 and 256 to the same number for proper CRT aspect ratio and the screen position will change slightly when playing games that change resolutions.

**To Reproduce**
1. Set horizontal width for both 320 and 256 to the same number
2. Play game that changes resolution (Sonic CD, Sonic 2, Castlevania, Monster World 4, etc.)
3. Observe screen shifting horizontally several pixels between 320 and 256 when the resolution change happens.

**Expected behavior**
320 and 256 modes should line up.

**Screenshots**
Don't have a way to take screenshots.

**Firmware version**
7.7

**Relevant Mega Sg settings**
Set horizontal width for both 320 and 256 to the same number.

**ROM name and hash values**
N/A

**Additional context**
Add any other context about the problem here: N/A

**Comment by Steven-Pendleton** [comment]
Got bored, made a video of it.

https://youtu.be/CHCxtdh6YIY 

I forgot to mention that I'm using the 1080 resolution, but maybe it's obvious since I'm using the 4x vertical resolution.

**Comment by tjanas** [comment]
@Steven-Pendleton Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
