### ISSUE TITLE
Request: Per-port pass-through mode with automatic fallback

### ISSUE THREAD

**Issue by WaferMouse** [SmokeMonsterPacks/Mega-Sg-Jailbreak#74]
Currently, if the user is using an "exotic" controller (eg. a mouse), they have to enable pass-through mode. Doing so prevents accessing the system menu.

This could be remedied by allowing the user to enable pass-through mode on a per-port basis, so they can have a standard pad connected at the same time for accessing the menu.

If the Mega SG also silently fell back to pass-through mode when no standard pad is detected, then almost any MD-compatible peripheral would be plug and play. Peripheral ID would allow for this.

I know this isn't related specifically to the jailbreak, but ¯\\_(ツ)_/¯

**Comment by SmokeMonsterPacks** [comment]
This didn't show up in the latest update so I'm closing the request to focus attention on bugs.
