### ISSUE TITLE
Sailor Moon bottom row of pixels is glitched

### ISSUE THREAD

**Issue by Steven-Pendleton** [SmokeMonsterPacks/Mega-Sg-Jailbreak#75]
(do not submit bugs if you are using any means of powering your Mega Sg other than the OEM power supply. Only use the original PSU and USB cable when bug testing)

**Describe the bug**
Bottom row of pixels seems to display as entirely black and occasionally flickers on left side.

**To Reproduce**
1. Insert original cart
2. Run cart
3. Start first level
4. Observe flickering in bottom left corner.

**Expected behavior**
Bottom row of pixels should display properly and not flicker.

**Video**
https://youtu.be/Ny96U7j7Vfg

**Firmware version**
7.7

**Relevant Mega Sg settings**
Seems to happen on any settings, including changing buffer modes and hiding/unhiding overscan area or CRAM dots.

**ROM name and hash values**
N/A. Using real cart.

**Additional context**
Does not occur on my real Japanese Mega Drive.

**Comment by tjanas** [comment]
@Steven-Pendleton Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB

**Comment by tjanas** [comment]
Per JB7.9 changelog:
Fixed Bishoujo Senshi Sailor Moon bottom row of glitchy pixels.
