### ISSUE TITLE
Sound corruption in Titan Megademo when run from SD card

### ISSUE THREAD

**Issue by TreacleWench** [SmokeMonsterPacks/Mega-Sg-Jailbreak#76]
As the title suggests, all audio is badly corrupted in the Titan Megademo when run from the SD card. It works fine when run from an Everdrive X5.

**Comment by G-Spindash** [comment]
Can confirm this has happened to me too. Haven't found a way to make it happen conistently though.

**Comment by G-Spindash** [comment]
Actually, scratch that, found a way. Can't verify on everdrive as I don't have one.

JB FW 7.7 From SD card, Run "Bad Apple!!" (8mb) FMV, then switch to Titan, sound is corrupted. 

Can provide Roms if necessary.

**Comment by tjanas** [comment]
@TreacleWench @G-Spindash Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB

**Comment by tjanas** [comment]
Per JB7.9 changelog:
Fixed sound corruption in Titan Mega Demo after running Bad Apple (and other conditions).
