### ISSUE TITLE
Unable to access in-game menu on Mega Everdrive (pre-X series model)

### ISSUE THREAD

**Issue by shawn** [SmokeMonsterPacks/Mega-Sg-Jailbreak#8]
## Expected behavior and actual behavior
I have an earlier model Mega Everdrive. Unsure if this would be considered the V1 or V2 model, but pre-X3/X5/X7 series. On a stock Genesis, pressing START+Down on the controller will open the in-game menu to access save state settings. On the Mega Sg, this key combination fails to switch into the in-game menu.

Here are two screenshots from the Mega Everdrive's settings, in case any options are relevant:

![IMG_1672](https://user-images.githubusercontent.com/10295/55523547-d2c85a80-5657-11e9-9955-6b4e791a5cfb.JPG)

![IMG_1673](https://user-images.githubusercontent.com/10295/55523550-d3f98780-5657-11e9-88e7-4fc3ec10ba2a.JPG)

## Steps to reproduce the problem
Press START+Down during game play. The Mega Everdrive should switch into the in-game menu automatically.

## firmware version
Tested with both official firmware v4.2, 4.3 and Jailbreak Firmware v7.3.

Also tested using both an original wired 3-button Genesis controller and an 8bitdo 2.4g wireless controller, just to rule out it wasn't a specific controller issue.

## relevant Mega Sg settings
Also tested with both controllers in "Passthrough Mode" as well as "Hotkeys Disabled." Also ensured that no existing Mega Sg hotkey shortcuts were set to the same START+Down key combinations.

**Comment by frederic-mahe** [comment]
Can someone please confirm this issue with earlier model Mega Everdrive?

**Comment by GreatHierophant** [comment]
Yes, the in-game menu on the original Mega EverDrive (v1) does not work at this time.  The MegaEverDrive X7 was originally called the Mega EverDrive v2 and it's in-game menu works with a cartridge released under either name.

**Comment by AC6y86** [comment]
I have a mega everdrive v2 and have the same issue, the menu doesn't come up.

**Comment by GreatHierophant** [comment]
The Mega EverDrive v2/X7's in-game menu shares the default hotkey for bringing up the Mega Sg menu.  You must change the Mega Sg's menu hotkey to something other than the default of Down + Start. Also, some games will not work right with the Mega ED's in-game menu.

**Comment by SmokeMonsterPacks** [comment]
Is this still present in v7.4?

**Comment by shawn** [comment]
Retested on v7.4 and issue is still present. 

Attempted with both "Passthrough Mode," as well as "Hotkeys Disabled," settings toggled on and off.

**Comment by Rustrock** [comment]
This issue is still present in v7.5.

**Comment by farhanjiwani** [comment]
I have a Mega Everdrive v2 (pre-X series) running OS Version 2.01. I had to enable the in-game menu in options before it would work for me (as expected). Also, my Mega SG is on JB firmware 7.7.

On the MED screen with the files listed, press C and you will have access to `Options`. Just make sure `In-Game Menu` is set to `ON`

**Comment by BamBam1963** [comment]
Same issue with my Mega Everdrive X5

**Comment by tjanas** [comment]
@shawn @BamBam1963 @Rustrock @AC6y86 please re-test with https://www.analogue.co/support/mega-sg/firmware/4.9

**Comment by tjanas** [comment]
@shawn @BamBam1963 @Rustrock @AC6y86 Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
