### ISSUE TITLE
Incorrect position of H and V between MSG and Super NT with DAC

### ISSUE THREAD

**Issue by Rageypoo** [SmokeMonsterPacks/Mega-Sg-Jailbreak#80]
**Describe the bug**
After getting the position exact using the 240p suite on the SNT, the MSG doesn't seem to have correct alignment. It is shifted to the right and slightly down, allowing the overscan to be visible during gameplay. If you correct the image to the MSG, the SNT suffers from an incorrect picture etc. 

**To Reproduce**
1. Align your geometry using 240p test suite to either the MSG or the SNT, either grid works
2. Load ROM, any will do but you can see it easily with Aladdin for md
3. Play through any level, it's immediate
4. See error shifted picture

**Expected behavior**
Despite using different resolutions, the grid should be aligned in the same manner across both devices @ 224p

**Screenshots**
Screenshots can be provided if needed, this issue is easy to reproduce. 

**Firmware version**
Latest firmware for both MSG and SNT (for DAC compatability)

**Additional context**
The SNT also uses a strange jitter effect, causing the picture to warp when scrolling from top to bottom. This may be causing the top portion of the MSG to not be properly aligned in the test suite as well, though that's just a speculation. 

**possible fix**

allowing adjustment of the H and V positions through the DAC similar to adjustments you can make on an LCD. 

**UPDATE**

I spoke with Kevtris about this and he agrees with the solution. The shifting seems to happen even on MSG individual cores so they each need their own HS slider to adjust screen positioning. He will be adding it in a future update though he didn't specify when.

**Comment by tjanas** [comment]
@Rageypoo Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
