### ISSUE TITLE
An option to dump your own cartridge games for Sega Genesis and Master System

### ISSUE THREAD

**Issue by krotz4** [SmokeMonsterPacks/Mega-Sg-Jailbreak#82]
I'd love to be able to dump my games onto the onboard SD Card. A Retrode for such a use isn't always the best option . I'd love to dump my Phantasy Star game that has issues with it.

**Comment by frederic-mahe** [comment]
Duly noted (same as issue #44).

**Comment by resistcorp** [comment]
I'm looking for this exact feature. I see it's marked as completed, but can't find it in the menus, using the latest jailbreak. Is it in there ?

**Comment by Kypck** [comment]
Bump.
I have bootleg of Shadow Dancer/Dangerous Seed that I would like to dump.
Seems they messed with the Dangerous seed part a bit and I would like to preserve (and share) this obscurity.
