### ISSUE TITLE
SMS increase Width/Height

### ISSUE THREAD

**Issue by G-Spindash** [SmokeMonsterPacks/Mega-Sg-Jailbreak#84]
Would it be possible to increase the width & height thresholds for SMS (presumably Colecovision too)?

So that the top & bottom of active SMS resolution can line up with top & bottom of screen, eliminating overscan borders, regardless of crop settings.

More of an issue with 720P which has slightly bigger borders.

**Comment by SmokeMonsterPacks** [comment]
This didn't show up in the latest update so I'm closing the request to focus attention on bugs.
