### ISSUE TITLE
reset instruction bug

### ISSUE THREAD

**Issue by krikzz** [SmokeMonsterPacks/Mega-Sg-Jailbreak#89]
After reset instruction execution system start data fetching from cart before than reset signal (vres B27) actually released. It may result crashes if console used in pair with reset sensitive devices (flashcarts, for example).
Some rare games may using this instruction, here is few of them: 
Risk, Paperboy 2, Boxing legends of the ring.
Can be reproduces on Mega EverDrive PRO with OS V4.02 or older versions

![reset](https://user-images.githubusercontent.com/27894092/107117407-d3992b80-6882-11eb-9d54-6a5221ea0cec.png)

**Comment by tjanas** [comment]
@krikzz please re-test with https://www.analogue.co/support/mega-sg/firmware/4.9

**Comment by tjanas** [comment]
@krikzz Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB

**Comment by tjanas** [comment]
Per JB7.9 changelog:
Fixed RESET instruction's output so reset is only asserted during the instruction.
