### ISSUE TITLE
bus timings bug

### ISSUE THREAD

**Issue by krikzz** [SmokeMonsterPacks/Mega-Sg-Jailbreak#90]
In specific conditions bus read cycle may be shorter than usually. This results Virtua Racing crashes on EverDrive when select "Free Run". Seems it sometimes happen after write cycles to the VDP data port (0xC00000) in pair with dbra instruction followed. In buggy read cycle, timings between as, cas0, ce_0, asel looks differently and  cycle is shorter than usually.  In case of buggy cycle console fetch data before than valid value (0xFFF8) placed on the bus.
Can be reproduces on Mega EverDrive PRO with OS V4.10 or older versions.

![ok](https://user-images.githubusercontent.com/27894092/107117802-72bf2280-6885-11eb-99f8-35256d0545fe.png)
![err](https://user-images.githubusercontent.com/27894092/107117801-72268c00-6885-11eb-8f21-a16f2fe3d624.png)

**Comment by xtcrefugee** [comment]
Free Run appears to work fine in VR on a Mega SD. Maybe it's a Mega EverDrive PRO bug?

**Comment by krikzz** [comment]
> Free Run appears to work fine in VR on a Mega SD. Maybe it's a Mega EverDrive PRO bug?

I made faster rom access and now it works on mega ed also, but on original console it worked fine without that fix. This behavior isn’t exist on original hardware. It may affect some other games, especially originals carts which often had pretty slow rom chips.

**Comment by tjanas** [comment]
@krikzz please re-test with https://www.analogue.co/support/mega-sg/firmware/4.9

**Comment by tjanas** [comment]
@krikzz Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB

**Comment by tjanas** [comment]
Per JB7.9 changelog:
Fixed bus timing issue after certain writes - this affected Virtua Racing in some situations.
