### ISSUE TITLE
320 and 256 Display Aspect Ratio formula incorrect for MD core:

### ISSUE THREAD

**Issue by Firebrandx** [SmokeMonsterPacks/Mega-Sg-Jailbreak#94]
I forgot to post this bug report last time, so I'm getting it done now after the latest firmware (JB 7.8). The problem is the formula for DAR is off on the MD core for 320 and 256 horizontal res. I had to measure the 'normally' active pixels in a paint program since the menu width settings are based on overscan. Below are 5x and 4x examples showing the currently incorrect labels, and the correct values they should be at to honor the correct DAR  formula:

Genesis 256: 

4:3 for 16:9 -  5x 1530 (wrong), 1554 (correct).
4:3 for 16:10 - 5x 1699 (wrong), 1725 (correct).

4:3 for 16:9 -  4x 1224 (wrong), 1243 (correct).
4:3 for 16:10 - 4x 1360 (wrong), 1381 (correct), remove the "5x256" part of the label as well.

**Comment by tjanas** [comment]
@Firebrandx Please re-test with JB7.9 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB

**Comment by Firebrandx** [comment]
I won't be able to do testing until next month as I'm moving into my new place. My apologies, but I will have them done in a few weeks with new videos! Cheers!

**Comment by tjanas** [comment]
Good luck on the move!

**Comment by Firebrandx** [comment]
Thanks! Shouldn't need much luck as it's literally right across the street. LOL!
