### ISSUE TITLE
Demons of Asteborg rom crashes

### ISSUE THREAD

**Issue by retiras** [SmokeMonsterPacks/Mega-Sg-Jailbreak#98]
**Describe the bug**
Demons of Asteborg rom crashes at the beginning of the first stage.

**Firmware version**
Latest 7.8 Version Jailbreak / v4.8 Official.

**ROM name and hash values**
Demons of Asteborg (World) (Aftermarket) (Unl).md
CRC32:
753bfc8f
MD5:
1abb8fc4e67b6e10d7902f2c8f3be7e4
SHA-1:
2c59f4fa40a5e4da012f8fb3aa4970a8f462f1f4

Demons of Asteborg.bin
CRC32:
02eeb7b3
MD5:
8c78f0ccd4a9006546d9f16cf11c5029
SHA-1:
afa42277dd459432b3e1ed7c582adc35997fa7c5

**Comment by Steven-Pendleton** [comment]
Where did you get this ROM? This looks like some pirate version, judging by that (World) (Aftermarket) (Unl) stuff. Mine is from the Kickstarter, emailed directly to me by Neofid, and ROM Hasher gives me these values:

ROM CRC32    67283FBE
ROM SHA-1    98A143B2312A062D640952700CD0D2DB78326FE2

Regardless, I get something different on 7.8 when run from the SD card slot: garbled intro, then a functional menu, then rather than crashing when I start the game, I get a garbled screen and I fall to my death repeatedly.

**Comment by retiras** [comment]
> Where did you get this ROM? This looks like some pirate version, judging by that (World) (Aftermarket) (Unl) stuff. Mine is from the Kickstarter, emailed directly to me by Neofid, and ROM Hasher gives me these values:
> 
> ROM CRC32 67283FBE
> ROM SHA-1 98A143B2312A062D640952700CD0D2DB78326FE2
> 
> Regardless, I get something different on 7.8 when run from the SD card slot: garbled intro, then a functional menu, then rather than crashing when I start the game, I get a garbled screen and I fall to my death repeatedly.

It´s from the last no-intro romset and I have the same issue. You explained it better.

**Comment by ShinKaz** [comment]
Same issue here, rom from KS too.

**Comment by itsTrifle** [comment]
FYI I get similar issues with the v1.1 ROM (from Steam installation)
* Neofid logo animation gfx & sound garbled
* Attract sequence freezes during a fade to white 
* Black screen when starting game 

CRC32 AACB216E

**Comment by jtorrad** [comment]
I also experienced the same issues with 1.1 ROM (I bought a physical cartridge) on 7.8 jailbreak.
SHA1 7525D9F54667B2E26FEAEA265F16316E2C7D96EC

issue description:
* gabled graphics and sound from logo animation
* functional start menu
* garbled graphics with the continuously character falling

**Comment by ProjectLittleMan** [comment]
> Where did you get this ROM? This looks like some pirate version, judging by that (World) (Aftermarket) (Unl) stuff. Mine is from the Kickstarter, emailed directly to me by Neofid, and ROM Hasher gives me these values:
> 
> ROM CRC32 67283FBE ROM SHA-1 98A143B2312A062D640952700CD0D2DB78326FE2
> 
> Regardless, I get something different on 7.8 when run from the SD card slot: garbled intro, then a functional menu, then rather than crashing when I start the game, I get a garbled screen and I fall to my death repeatedly.

We learned today that this specific ROM was leaked by the DoA team as an anti piracy mechanism. 
![image](https://user-images.githubusercontent.com/93239553/148275483-cc2b0820-c77e-4cc0-9dc5-8f09171a3c0e.jpeg)

**Comment by tjanas** [comment]
@jtorrad can you test your physical cartridge with https://www.analogue.co/support/mega-sg/firmware/4.9

**Comment by BooBerry** [comment]
I tested the latest ROM of Demons of Asteborg (v.1.11) on both the MegaSD and Mega Everdrive Pro and the game works fine on both on the Mega Sg with the 4.9 firmware.

**Comment by L10N37** [comment]
@BooBerry 

I only purchased the ROM and use a Jail Broken FW :( i've owned it since release and never being able to try it.

**Comment by tjanas** [comment]
@L10N37 please try JB7.9 and if that does not resolve the issue, please open a ticket at https://github.com/analoguejb/Analogue-Mega-Sg-JB
