### ISSUE TITLE
Colecovision Controller keypad not working

### ISSUE THREAD

**Issue by douglie007** [SmokeMonsterPacks/Mega-Sg-Jailbreak#99]
(please note that feature requests will be marked as **closed** after a couple days to maintain the focus on unresolved bugs)

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]  I can't use the Original coleco controllers keypad..

**Describe the solution you'd like**

I would like to be able to use all the coleco controllers and sms controllers

**Describe alternatives you've considered**
I would like to use the keypad on the original controller when playing the core. 
**Additional context**

I don't know if it's  a bug or a feature request but the colecovision core I can use the original controller but the keypad doesn't register any inputs but it works on the coleco.  So I would like the ability to use all of the original coleco and sms controllers on the console.

**Comment by tjanas** [comment]
@douglie007 please open feature requests on the new JB repo https://github.com/analoguejb/Analogue-Mega-Sg-JB
